version: "3.7"
services:
  database:
    build:
      context: .
      dockerfile: ./db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
      MYSQL_ROOT_HOST: "%"
    container_name: yondonce-db
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - 33068:3306
    volumes:
      - mysql_db_volume:/var/lib/mysql

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080

volumes:
  mysql_db_volume:
